# Generated by Django 5.1.4 on 2024-12-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saccounts', '0002_librarian_staff_student_libraryform_feesform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
    ]
