# Generated by Django 5.1.4 on 2024-12-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccounts', '0004_librarian_user_staff_user_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='subjects',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Maths', 'Maths'), ('librarian', 'librarian')], default='Physics', max_length=50),
        ),
        migrations.DeleteModel(
            name='Librarian',
        ),
    ]
