# Generated by Django 5.1.4 on 2024-12-15 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccounts', '0005_alter_staff_subjects_delete_librarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesform',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saccounts.student'),
        ),
        migrations.AlterField(
            model_name='libraryform',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saccounts.student'),
        ),
    ]
